export const categories = [
  { id: 1, title: "All categories", },
  { id: 2, title: "Morning", },
  { id: 3, title: "Education", },
  { id: 4, title: "Art", },
  { id: 5, title: "Stories", },
  { id: 6, title: "History", },
  { id: 7, title: "Space", },
  { id: 8, title: "Literature", },
  { id: 9, title: "Information technology", },
];
  
// "Region",
// "Education",
// "Art",
// "Stories",
// "History",
// "Space",
// "Literature",
// "Information technology",